/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WakeUpConfig {
  homeAdress?: string;
  officeAdress?: string;
  localTimeZone?: string;
  noWakeUpBefore?: number;
  preferedWorkingType?: "home" | "office";
  officeWorkingConfig?: WorkingConfig;
  homeWorkingConfig?: WorkingConfig;
}
export interface WorkingConfig {
  shouldStartAt?: number;
  delay?: number;
  preparationDuration?: number;
  configChecks?: ConfigChecks;
}
export interface ConfigChecks {
  weatherCheck?: WeatherCheck;
  airPollutionCheck?: AirPollutionCheck;
  agendaCheck?: AgendaCheck;
  directionCheck?: DirectionCheck;
}
export interface WeatherCheck {
  minTemp?: number;
  maxTemp?: number;
  weatherConditions?: WeatherCondition[];
}
export interface WeatherCondition {
  type?: string;
  maxIntensity?: number;
}
export interface AirPollutionCheck {
  minAqi?: number;
}
export interface AgendaCheck {
  url?: string;
}
export interface DirectionCheck {
  car?: boolean;
  bus?: boolean;
  train?: boolean;
  bike?: boolean;
  walk?: boolean;
}
